### ISSUE TITLE
[LOW] Write Config + enso:role:sync

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/roles#27]
This is  a **question**.

Hi,

Is the WriteConfig + enso:role:sync command still functional and supported by latest Laravel-Enso 4.8.0? 
Is this command supposed to import roles from one laravel-enso instance to another (ex: PROD->DEV)?

We figured out a bit how it's supposed to work, but it is not working properly, and we thought maybe it's a dead feature.

If still used and functional on your side, let me know, maybe we also contribute with some documentation on this feature, and figure out what's wrong in our situation... (or there is a documentation already, can you point us to it?)

**Comment by robbykrlos** [comment]
PS: php artisan enso:roles:add-missing-permission doesn't exists anymore

**Comment by aocneanu** [comment]
`enso:roles:sync` is the recommended way to keep dev & prod roles in sync.

The ideal workflow is creating new roles with seeders (or upgrade commands and update in seeders), then configuring roles only in dev env and running roles:sync in the deployment process.
